package com.skan.potal.web.potal.address.model;

import java.io.Serializable;

import javax.persistence.Embeddable;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * 주소 composite - id 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Embeddable
public class HmAddressInfoId implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 주소록 관리. */
	@ManyToOne
	@JoinColumn(name="hmMgNum")
	private HmMngAddress hmMngAddress;

	/** 순번. */
	private Long hmAdNo;

	/**
	 * 생성자.
	 */
	public HmAddressInfoId() {
	}

	/**
	 * 주소록 관리을 설정합니다..
	 * 
	 * @param hmMngAddress
	 *            주소록 관리
	 */
	public void setHmMngAddress(HmMngAddress hmMngAddress) {
		this.hmMngAddress = hmMngAddress;
	}

	/**
	 * 주소록 관리을 가져옵니다..
	 * 
	 * @return 주소록 관리
	 */
	public HmMngAddress getHmMngAddress() {
		return this.hmMngAddress;
	}

	/**
	 * 순번을 설정합니다..
	 * 
	 * @param hmAdNo
	 *            순번
	 */
	public void setHmAdNo(Long hmAdNo) {
		this.hmAdNo = hmAdNo;
	}

	/**
	 * 순번을 가져옵니다..
	 * 
	 * @return 순번
	 */
	public Long getHmAdNo() {
		return this.hmAdNo;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((hmMngAddress == null) ? 0 : hmMngAddress.hashCode());
		result = prime * result + ((hmAdNo == null) ? 0 : hmAdNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		HmAddressInfoId other = (HmAddressInfoId) obj;
		if (hmMngAddress == null) {
			if (other.hmMngAddress != null) {
				return false;
			}
		} else if (!hmMngAddress.equals(other.hmMngAddress)) {
			return false;
		}
		if (hmAdNo == null) {
			if (other.hmAdNo != null) {
				return false;
			}
		} else if (!hmAdNo.equals(other.hmAdNo)) {
			return false;
		}
		return true;
	}

}
