package com.skan.potal.web.potal.address.model;

import java.io.Serializable;
import java.util.Date;

/**
 * 기념일 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class HmAnniversaryMng implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 기념일 composite - id. */
	private HmAnniversaryMngId hmAnniversaryMngId;

	/** 주소록 관리. */
	private HmMngAddress hmMgNohmMngAddress;

	/** 날짜. */
	private Date hmDate;

	/** 구분. */
	private String hmType;

	/**
	 * 생성자.
	 */
	public HmAnniversaryMng() {
	}

	/**
	 * 기념일 composite - id을 설정합니다..
	 * 
	 * @param hmAnniversaryMngId
	 *            기념일 composite - id
	 */
	public void setHmAnniversaryMngId(HmAnniversaryMngId hmAnniversaryMngId) {
		this.hmAnniversaryMngId = hmAnniversaryMngId;
	}

	/**
	 * 기념일 composite - id을 가져옵니다..
	 * 
	 * @return 기념일 composite - id
	 */
	public HmAnniversaryMngId getHmAnniversaryMngId() {
		return this.hmAnniversaryMngId;
	}

	/**
	 * 주소록 관리을 설정합니다..
	 * 
	 * @param hmMgNohmMngAddress
	 *            주소록 관리
	 */
	public void setHmMgNohmMngAddress(HmMngAddress hmMgNohmMngAddress) {
		this.hmMgNohmMngAddress = hmMgNohmMngAddress;
	}

	/**
	 * 주소록 관리을 가져옵니다..
	 * 
	 * @return 주소록 관리
	 */
	public HmMngAddress getHmMgNohmMngAddress() {
		return this.hmMgNohmMngAddress;
	}

	/**
	 * 날짜을 설정합니다..
	 * 
	 * @param hmDate
	 *            날짜
	 */
	public void setHmDate(Date hmDate) {
		this.hmDate = hmDate;
	}

	/**
	 * 날짜을 가져옵니다..
	 * 
	 * @return 날짜
	 */
	public Date getHmDate() {
		return this.hmDate;
	}

	/**
	 * 구분을 설정합니다..
	 * 
	 * @param hmType
	 *            구분
	 */
	public void setHmType(String hmType) {
		this.hmType = hmType;
	}

	/**
	 * 구분을 가져옵니다..
	 * 
	 * @return 구분
	 */
	public String getHmType() {
		return this.hmType;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((hmAnniversaryMngId == null) ? 0 : hmAnniversaryMngId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		HmAnniversaryMng other = (HmAnniversaryMng) obj;
		if (hmAnniversaryMngId == null) {
			if (other.hmAnniversaryMngId != null) {
				return false;
			}
		} else if (!hmAnniversaryMngId.equals(other.hmAnniversaryMngId)) {
			return false;
		}
		return true;
	}

}
