package com.skan.potal.web.potal.address.model;

import java.io.Serializable;

/**
 * 기념일 composite - id 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class HmAnniversaryMngId implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 주소록 관리. */
	private HmMngAddress hmMgNohmMngAddress;

	/** 순번. */
	private Long hmAmNo;

	/**
	 * 생성자.
	 */
	public HmAnniversaryMngId() {
	}

	/**
	 * 주소록 관리을 설정합니다..
	 * 
	 * @param hmMgNohmMngAddress
	 *            주소록 관리
	 */
	public void setHmMgNohmMngAddress(HmMngAddress hmMgNohmMngAddress) {
		this.hmMgNohmMngAddress = hmMgNohmMngAddress;
	}

	/**
	 * 주소록 관리을 가져옵니다..
	 * 
	 * @return 주소록 관리
	 */
	public HmMngAddress getHmMgNohmMngAddress() {
		return this.hmMgNohmMngAddress;
	}

	/**
	 * 순번을 설정합니다..
	 * 
	 * @param hmAmNo
	 *            순번
	 */
	public void setHmAmNo(Long hmAmNo) {
		this.hmAmNo = hmAmNo;
	}

	/**
	 * 순번을 가져옵니다..
	 * 
	 * @return 순번
	 */
	public Long getHmAmNo() {
		return this.hmAmNo;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((hmMgNohmMngAddress == null) ? 0 : hmMgNohmMngAddress.hashCode());
		result = prime * result + ((hmAmNo == null) ? 0 : hmAmNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		HmAnniversaryMngId other = (HmAnniversaryMngId) obj;
		if (hmMgNohmMngAddress == null) {
			if (other.hmMgNohmMngAddress != null) {
				return false;
			}
		} else if (!hmMgNohmMngAddress.equals(other.hmMgNohmMngAddress)) {
			return false;
		}
		if (hmAmNo == null) {
			if (other.hmAmNo != null) {
				return false;
			}
		} else if (!hmAmNo.equals(other.hmAmNo)) {
			return false;
		}
		return true;
	}

}
