package com.skan.potal.web.potal.address.model;

import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * 이메일 정보 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table
public class HmEmailInfo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 이메일 정보 composite - id. */
	@EmbeddedId private HmEmailInfoId hmEmailInfoId;

	/** 주소록 관리. */
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="hmMgNum",insertable=false, updatable=false)
	private HmMngAddress hmMngAddress;

	/** 이메일. */
	private String hmEmail;

	/**
	 * 생성자.
	 */
	public HmEmailInfo() {
	}

	/**
	 * 이메일 정보 composite - id을 설정합니다..
	 * 
	 * @param hmEmailInfoId
	 *            이메일 정보 composite - id
	 */
	public void setHmEmailInfoId(HmEmailInfoId hmEmailInfoId) {
		this.hmEmailInfoId = hmEmailInfoId;
	}

	/**
	 * 이메일 정보 composite - id을 가져옵니다..
	 * 
	 * @return 이메일 정보 composite - id
	 */
	public HmEmailInfoId getHmEmailInfoId() {
		return this.hmEmailInfoId;
	}

	/**
	 * 주소록 관리을 설정합니다..
	 * 
	 * @param hmMngAddress
	 *            주소록 관리
	 */
	public void setHmMngAddress(HmMngAddress hmMngAddress) {
		this.hmMngAddress = hmMngAddress;
	}

	/**
	 * 주소록 관리을 가져옵니다..
	 * 
	 * @return 주소록 관리
	 */
	public HmMngAddress getHmMngAddress() {
		return this.hmMngAddress;
	}

	/**
	 * 이메일을 설정합니다..
	 * 
	 * @param hmEmail
	 *            이메일
	 */
	public void setHmEmail(String hmEmail) {
		this.hmEmail = hmEmail;
	}

	/**
	 * 이메일을 가져옵니다..
	 * 
	 * @return 이메일
	 */
	public String getHmEmail() {
		return this.hmEmail;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((hmEmailInfoId == null) ? 0 : hmEmailInfoId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		HmEmailInfo other = (HmEmailInfo) obj;
		if (hmEmailInfoId == null) {
			if (other.hmEmailInfoId != null) {
				return false;
			}
		} else if (!hmEmailInfoId.equals(other.hmEmailInfoId)) {
			return false;
		}
		return true;
	}

}
