package com.skan.potal.web.potal.accountbook.dto;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

/**
 * 가계부(house_keeping_book) 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table
public class DomesticAccountBook implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 관리번호. */
	@Id
	private String dabMngNo;
	
	/** 개인코드. */
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="type_code", updatable=true,nullable=true)
	private PersonalCode typePersonalCode;

	/** 거래일. */
	@DateTimeFormat(iso=ISO.DATE)
	@Temporal(TemporalType.DATE)
	private Date businessDay;

	/** 금액. */
	private Long amount;

	/** 내역. */
	private String breakdown;

	/** 세부내용. */
	private String detailContents;

	/**
	 * 생성자.
	 */
	public DomesticAccountBook() {
	}

	/**
	 * 관리번호을 설정합니다..
	 * 
	 * @param dabMngNo
	 *            관리번호
	 */
	public void setDabMngNo(String dabMngNo) {
		this.dabMngNo = dabMngNo;
	}

	/**
	 * 관리번호을 가져옵니다..
	 * 
	 * @return 관리번호
	 */
	public String getDabMngNo() {
		return this.dabMngNo;
	}

	/**
	 * 개인코드을 설정합니다..
	 * 
	 * @param typePersonalCode
	 *            개인코드
	 */
	public void setTypePersonalCode(PersonalCode typePersonalCode) {
		this.typePersonalCode = typePersonalCode;
	}

	/**
	 * 개인코드을 가져옵니다..
	 * 
	 * @return 개인코드
	 */
	public PersonalCode getTypePersonalCode() {
		return this.typePersonalCode;
	}

	/**
	 * 거래일을 설정합니다..
	 * 
	 * @param businessDay
	 *            거래일
	 */
	public void setBusinessDay(Date businessDay) {
		this.businessDay = businessDay;
	}

	/**
	 * 거래일을 가져옵니다..
	 * 
	 * @return 거래일
	 */
	public Date getBusinessDay() {
		return this.businessDay;
	}

	/**
	 * 금액을 설정합니다..
	 * 
	 * @param amount
	 *            금액
	 */
	public void setAmount(Long amount) {
		this.amount = amount;
	}

	/**
	 * 금액을 가져옵니다..
	 * 
	 * @return 금액
	 */
	public Long getAmount() {
		return this.amount;
	}

	/**
	 * 내역을 설정합니다..
	 * 
	 * @param breakdown
	 *            내역
	 */
	public void setBreakdown(String breakdown) {
		this.breakdown = breakdown;
	}

	/**
	 * 내역을 가져옵니다..
	 * 
	 * @return 내역
	 */
	public String getBreakdown() {
		return this.breakdown;
	}

	/**
	 * 세부내용을 설정합니다..
	 * 
	 * @param detailContents
	 *            세부내용
	 */
	public void setDetailContents(String detailContents) {
		this.detailContents = detailContents;
	}

	/**
	 * 세부내용을 가져옵니다..
	 * 
	 * @return 세부내용
	 */
	public String getDetailContents() {
		return this.detailContents;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((dabMngNo == null) ? 0 : dabMngNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		DomesticAccountBook other = (DomesticAccountBook) obj;
		if (dabMngNo == null) {
			if (other.dabMngNo != null) {
				return false;
			}
		} else if (!dabMngNo.equals(other.dabMngNo)) {
			return false;
		}
		return true;
	}

}
