package com.skan.potal.web.potal.cattle.dto;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * 질병 및 치료 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table
public class HmCattleCureInfo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 질병 및 치료 composite - id. */
	@EmbeddedId private HmCattleCureInfoId hmCattleCureInfoId;

	/** 날짜. */
	private Date cureDate;

	/** 질병 이름. */
	private String diseaseName;

	/** 치료내역/약제이름. */
	private String cureBrakdown;

	/** 투여방법. */
	private String injectionMethod;

	/** 휴약기간만료일. */
	private Date withdrawalPeriodExpirationDate;

	/** 주사침분실여부. */
	private String needleLoseYn;

	/** 한우(암소/수소) 개체관리기록부. */
	@ManyToOne
	@JoinColumn(name="entityDiscernNo" ,insertable=false, updatable=false)
	private HmCattleRegister hmCattleRegister;

	/**
	 * 생성자.
	 */
	public HmCattleCureInfo() {
	}

	/**
	 * 질병 및 치료 composite - id을 설정합니다..
	 * 
	 * @param hmCattleCureInfoId
	 *            질병 및 치료 composite - id
	 */
	public void setHmCattleCureInfoId(HmCattleCureInfoId hmCattleCureInfoId) {
		this.hmCattleCureInfoId = hmCattleCureInfoId;
	}

	/**
	 * 질병 및 치료 composite - id을 가져옵니다..
	 * 
	 * @return 질병 및 치료 composite - id
	 */
	public HmCattleCureInfoId getHmCattleCureInfoId() {
		return this.hmCattleCureInfoId;
	}

	/**
	 * 날짜을 설정합니다..
	 * 
	 * @param cureDate
	 *            날짜
	 */
	public void setCureDate(Date cureDate) {
		this.cureDate = cureDate;
	}

	/**
	 * 날짜을 가져옵니다..
	 * 
	 * @return 날짜
	 */
	public Date getCureDate() {
		return this.cureDate;
	}

	/**
	 * 질병 이름을 설정합니다..
	 * 
	 * @param diseaseName
	 *            질병 이름
	 */
	public void setDiseaseName(String diseaseName) {
		this.diseaseName = diseaseName;
	}

	/**
	 * 질병 이름을 가져옵니다..
	 * 
	 * @return 질병 이름
	 */
	public String getDiseaseName() {
		return this.diseaseName;
	}

	/**
	 * 치료내역/약제이름을 설정합니다..
	 * 
	 * @param cureBrakdown
	 *            치료내역/약제이름
	 */
	public void setCureBrakdown(String cureBrakdown) {
		this.cureBrakdown = cureBrakdown;
	}

	/**
	 * 치료내역/약제이름을 가져옵니다..
	 * 
	 * @return 치료내역/약제이름
	 */
	public String getCureBrakdown() {
		return this.cureBrakdown;
	}

	/**
	 * 투여방법을 설정합니다..
	 * 
	 * @param injectionMethod
	 *            투여방법
	 */
	public void setInjectionMethod(String injectionMethod) {
		this.injectionMethod = injectionMethod;
	}

	/**
	 * 투여방법을 가져옵니다..
	 * 
	 * @return 투여방법
	 */
	public String getInjectionMethod() {
		return this.injectionMethod;
	}

	/**
	 * 휴약기간만료일을 설정합니다..
	 * 
	 * @param withdrawalPeriodExpirationDate
	 *            휴약기간만료일
	 */
	public void setWithdrawalPeriodExpirationDate(Date withdrawalPeriodExpirationDate) {
		this.withdrawalPeriodExpirationDate = withdrawalPeriodExpirationDate;
	}

	/**
	 * 휴약기간만료일을 가져옵니다..
	 * 
	 * @return 휴약기간만료일
	 */
	public Date getWithdrawalPeriodExpirationDate() {
		return this.withdrawalPeriodExpirationDate;
	}

	/**
	 * 주사침분실여부을 설정합니다..
	 * 
	 * @param needleLoseYn
	 *            주사침분실여부
	 */
	public void setNeedleLoseYn(String needleLoseYn) {
		this.needleLoseYn = needleLoseYn;
	}

	/**
	 * 주사침분실여부을 가져옵니다..
	 * 
	 * @return 주사침분실여부
	 */
	public String getNeedleLoseYn() {
		return this.needleLoseYn;
	}

	/**
	 * 한우(암소/수소) 개체관리기록부을 설정합니다..
	 * 
	 * @param hmCattleRegister
	 *            한우(암소/수소) 개체관리기록부
	 */
	public void setHmCattleRegister(HmCattleRegister hmCattleRegister) {
		this.hmCattleRegister = hmCattleRegister;
	}

	/**
	 * 한우(암소/수소) 개체관리기록부을 가져옵니다..
	 * 
	 * @return 한우(암소/수소) 개체관리기록부
	 */
	public HmCattleRegister getHmCattleRegister() {
		return this.hmCattleRegister;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((hmCattleCureInfoId == null) ? 0 : hmCattleCureInfoId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		HmCattleCureInfo other = (HmCattleCureInfo) obj;
		if (hmCattleCureInfoId == null) {
			if (other.hmCattleCureInfoId != null) {
				return false;
			}
		} else if (!hmCattleCureInfoId.equals(other.hmCattleCureInfoId)) {
			return false;
		}
		return true;
	}

}
