package com.skan.potal.web.potal.accountbook.model;

import java.util.Date;

import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

/**
 * 가계부(house_keeping_book) 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class DomesticAccountBookModel {

	/** 관리번호. */
	private String dabMngNo;

	/** 개인코드. */
	private String typeCode;

	/** 거래일. */
	@DateTimeFormat(iso=ISO.DATE)
	private Date businessDay;

	/** 금액. */
	private Long amount;

	/** 내역. */
	private String breakdown;

	/** 세부내용. */
	private String detailContents;

	/**
	 * 생성자.
	 */
	public DomesticAccountBookModel() {
	}

	/**
	 * 관리번호을 설정합니다..
	 * 
	 * @param dabMngNo
	 *            관리번호
	 */
	public void setDabMngNo(String dabMngNo) {
		this.dabMngNo = dabMngNo;
	}

	/**
	 * 관리번호을 가져옵니다..
	 * 
	 * @return 관리번호
	 */
	public String getDabMngNo() {
		return this.dabMngNo;
	}


	public String getTypeCode() {
		return typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	/**
	 * 거래일을 설정합니다..
	 * 
	 * @param businessDay
	 *            거래일
	 */
	public void setBusinessDay(Date businessDay) {
		this.businessDay = businessDay;
	}

	/**
	 * 거래일을 가져옵니다..
	 * 
	 * @return 거래일
	 */
	public Date getBusinessDay() {
		return this.businessDay;
	}

	/**
	 * 금액을 설정합니다..
	 * 
	 * @param amount
	 *            금액
	 */
	public void setAmount(Long amount) {
		this.amount = amount;
	}

	/**
	 * 금액을 가져옵니다..
	 * 
	 * @return 금액
	 */
	public Long getAmount() {
		return this.amount;
	}

	/**
	 * 내역을 설정합니다..
	 * 
	 * @param breakdown
	 *            내역
	 */
	public void setBreakdown(String breakdown) {
		this.breakdown = breakdown;
	}

	/**
	 * 내역을 가져옵니다..
	 * 
	 * @return 내역
	 */
	public String getBreakdown() {
		return this.breakdown;
	}

	/**
	 * 세부내용을 설정합니다..
	 * 
	 * @param detailContents
	 *            세부내용
	 */
	public void setDetailContents(String detailContents) {
		this.detailContents = detailContents;
	}

	/**
	 * 세부내용을 가져옵니다..
	 * 
	 * @return 세부내용
	 */
	public String getDetailContents() {
		return this.detailContents;
	}

}
