package com.skan.potal.web.potal.cattle.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * 판매지정보 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table
public class HmCattleSellStoreInfo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;
  
	/** 판매처. */
	private String storeName;

	/** 판매/도태일자. */
	private Date sellDate;

	/** 비고. */
	private String sellNote;

	/** 판매 연락처. */
	private String sellPhoneNumber;
	
	@Id
	private String entityDiscernNo;

	/** 한우(암소/수소) 개체관리기록부. */
	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name="entityDiscernNo" , insertable=false, updatable=false)
	private HmCattleRegister hmCattleRegister;

	/**
	 * 생성자.
	 */
	public HmCattleSellStoreInfo() {
	}

	/**
	 * 판매처을 설정합니다..
	 * 
	 * @param storeName
	 *            판매처
	 */
	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	/**
	 * 판매처을 가져옵니다..
	 * 
	 * @return 판매처
	 */
	public String getStoreName() {
		return this.storeName;
	}

	/**
	 * 판매/도태일자을 설정합니다..
	 * 
	 * @param sellDate
	 *            판매/도태일자
	 */
	public void setSellDate(Date sellDate) {
		this.sellDate = sellDate;
	}

	/**
	 * 판매/도태일자을 가져옵니다..
	 * 
	 * @return 판매/도태일자
	 */
	public Date getSellDate() {
		return this.sellDate;
	}

	/**
	 * 비고을 설정합니다..
	 * 
	 * @param sellNote
	 *            비고
	 */
	public void setSellNote(String sellNote) {
		this.sellNote = sellNote;
	}

	/**
	 * 비고을 가져옵니다..
	 * 
	 * @return 비고
	 */
	public String getSellNote() {
		return this.sellNote;
	}

	/**
	 * 판매 연락처을 설정합니다..
	 * 
	 * @param sellPhoneNumber
	 *            판매 연락처
	 */
	public void setSellPhoneNumber(String sellPhoneNumber) {
		this.sellPhoneNumber = sellPhoneNumber;
	}

	/**
	 * 판매 연락처을 가져옵니다..
	 * 
	 * @return 판매 연락처
	 */
	public String getSellPhoneNumber() {
		return this.sellPhoneNumber;
	}

	/**
	 * 한우(암소/수소) 개체관리기록부을 설정합니다..
	 * 
	 * @param hmCattleRegister
	 *            한우(암소/수소) 개체관리기록부
	 */
	public void setHmCattleRegister(HmCattleRegister hmCattleRegister) {
		this.hmCattleRegister = hmCattleRegister;
	}

	/**
	 * 한우(암소/수소) 개체관리기록부을 가져옵니다..
	 * 
	 * @return 한우(암소/수소) 개체관리기록부
	 */
	public HmCattleRegister getHmCattleRegister() {
		return this.hmCattleRegister;
	}

	public String getEntityDiscernNo() {
		return entityDiscernNo;
	}

	public void setEntityDiscernNo(String entityDiscernNo) {
		this.entityDiscernNo = entityDiscernNo;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((hmCattleRegister == null) ? 0 : hmCattleRegister.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		HmCattleSellStoreInfo other = (HmCattleSellStoreInfo) obj;
		if (hmCattleRegister == null) {
			if (other.hmCattleRegister != null) {
				return false;
			}
		} else if (!hmCattleRegister.equals(other.hmCattleRegister)) {
			return false;
		}
		return true;
	}

}
