package com.skan.potal.web.potal.application.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 일정관리 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="cmtbschedule")
public class CmtbSchedule implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;
	
	/** 일정관리번호. */
	@Id
	private Long schMgtNo;

	/** 같은날의 순번. */
	@Id
	private Long schSeq;
	

	/** 제목. */
	private String schSubject;

	/** 내용. */
	private String schContent;

	/** 기준날짜. */
	private String stdDate;

	/** 오늘 날씨. */
	private String todayWeatherCode;

	/** 최저온도(영상/영하구분). */
	private String minDegreespointCode;

	/** 최고온도(영상/영하)구분. */
	private String maxDegreespointCode;

	/** 최저 기온. */
	private Long minTemperature;

	/** 최고온도. */
	private Long maxTemperature;

	/** 생성시간. */
	private Date createTime;

	/** 수정시간. */
	private Date modifyTime;

	/** 공개 여부. */
	private String publicYn;
	
	

	/**
	 * 일정관리번호을 설정합니다..
	 * 
	 * @param schMgtNo
	 *            일정관리번호
	 */
	public void setSchMgtNo(Long schMgtNo) {
		this.schMgtNo = schMgtNo;
	}

	/**
	 * 일정관리번호을 가져옵니다..
	 * 
	 * @return 일정관리번호
	 */
	public Long getSchMgtNo() {
		return this.schMgtNo;
	}

	/**
	 * 같은날의 순번을 설정합니다..
	 * 
	 * @param schSeq
	 *            같은날의 순번
	 */
	public void setSchSeq(Long schSeq) {
		this.schSeq = schSeq;
	}

	/**
	 * 같은날의 순번을 가져옵니다..
	 * 
	 * @return 같은날의 순번
	 */
	public Long getSchSeq() {
		return this.schSeq;
	}

	public String getSchSubject() {
		return schSubject;
	}

	public void setSchSubject(String schSubject) {
		this.schSubject = schSubject;
	}

	public String getSchContent() {
		return schContent;
	}

	public void setSchContent(String schContent) {
		this.schContent = schContent;
	}

	public String getStdDate() {
		return stdDate;
	}

	public void setStdDate(String stdDate) {
		this.stdDate = stdDate;
	}

	public String getTodayWeatherCode() {
		return todayWeatherCode;
	}

	public void setTodayWeatherCode(String todayWeatherCode) {
		this.todayWeatherCode = todayWeatherCode;
	}

	public String getMinDegreespointCode() {
		return minDegreespointCode;
	}

	public void setMinDegreespointCode(String minDegreespointCode) {
		this.minDegreespointCode = minDegreespointCode;
	}

	public String getMaxDegreespointCode() {
		return maxDegreespointCode;
	}

	public void setMaxDegreespointCode(String maxDegreespointCode) {
		this.maxDegreespointCode = maxDegreespointCode;
	}

	public Long getMinTemperature() {
		return minTemperature;
	}

	public void setMinTemperature(Long minTemperature) {
		this.minTemperature = minTemperature;
	}

	public Long getMaxTemperature() {
		return maxTemperature;
	}

	public void setMaxTemperature(Long maxTemperature) {
		this.maxTemperature = maxTemperature;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String getPublicYn() {
		return publicYn;
	}

	public void setPublicYn(String publicYn) {
		this.publicYn = publicYn;
	}

	
}
