package com.skan.potal.web.potal.application.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * 일정관리 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="cmtbschedule")
public class CmtbSchedule implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;
	
	@EmbeddedId private CmtbSchedulePK cmtbSchedulePK;
	
	/** 제목. */
	@NotEmpty
	private String schSubject;

	/** 내용. */
	private String schContent;

	/** 시작 날짜. */
	@NotNull
	private String stdDate;
	
	/** 종료 날짜	 */
	@NotNull
	private String endDate;

	/** 오늘 날씨. */
	private String todayWeatherCode;

	/** 최저온도(영상/영하구분). */
	private String minDegreespointCode;

	/** 최고온도(영상/영하)구분. */
	private String maxDegreespointCode;

	/** 최저 기온. */
	private Long minTemperature;

	/** 최고온도. */
	private Long maxTemperature;

	/** 생성시간. */
	private Date createTime;

	/** 수정시간. */
	private Date modifyTime;

	/** 공개 여부. */
	private String publicYn;
	
	private String userId;
	
	private Long groupNo;
	
	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Long getGroupNo() {
		return groupNo;
	}

	public void setGroupNo(Long groupNo) {
		this.groupNo = groupNo;
	}

	public String getSchSubject() {
		return schSubject;
	}

	public void setSchSubject(String schSubject) {
		this.schSubject = schSubject;
	}

	public String getSchContent() {
		return schContent;
	}

	public void setSchContent(String schContent) {
		this.schContent = schContent;
	}

	public String getStdDate() {
		return stdDate;
	}

	public void setStdDate(String stdDate) {
		this.stdDate = stdDate;
	}

	public String getTodayWeatherCode() {
		return todayWeatherCode;
	}

	public void setTodayWeatherCode(String todayWeatherCode) {
		this.todayWeatherCode = todayWeatherCode;
	}

	public String getMinDegreespointCode() {
		return minDegreespointCode;
	}

	public void setMinDegreespointCode(String minDegreespointCode) {
		this.minDegreespointCode = minDegreespointCode;
	}

	public String getMaxDegreespointCode() {
		return maxDegreespointCode;
	}

	public void setMaxDegreespointCode(String maxDegreespointCode) {
		this.maxDegreespointCode = maxDegreespointCode;
	}

	public Long getMinTemperature() {
		return minTemperature;
	}

	public void setMinTemperature(Long minTemperature) {
		this.minTemperature = minTemperature;
	}

	public Long getMaxTemperature() {
		return maxTemperature;
	}

	public void setMaxTemperature(Long maxTemperature) {
		this.maxTemperature = maxTemperature;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String getPublicYn() {
		return publicYn;
	}

	public void setPublicYn(String publicYn) {
		this.publicYn = publicYn;
	}

	public CmtbSchedulePK getCmtbSchedulePK() {
		return cmtbSchedulePK;
	}

	public void setCmtbSchedulePK(CmtbSchedulePK cmtbSchedulePK) {
		this.cmtbSchedulePK = cmtbSchedulePK;
	}
	
	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	@Override
	public String toString(){
		return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
	}

}
