package com.skan.potal.web.potal.application.model;

import java.io.Serializable;
import java.util.List;

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * 그룹멤버 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table
public class CmtbGroupMember implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 그룹멤버 composite - id. */
	@Id
	private String userId;
	
	@Id
	/** 그룹번호. */
	private Long groupNo;	

	/**
	 * 그룹 정보 
	 */
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="groupNo" ,insertable=false, updatable=false)
	private CmtbGroup cmtbGroup;
	
	/**
	 * 사용자 정보
	 */
	@OneToMany(fetch=FetchType.LAZY ,mappedBy="cmtbGroupMember")
	private List<CmtbUser> cmtbUserList;
	

	public List<CmtbUser> getCmtbUserList() {
		return cmtbUserList;
	}

	public void setCmtbUserList(List<CmtbUser> cmtbUserList) {
		this.cmtbUserList = cmtbUserList;
	}

	/** 일정관리 테이블 목록. */
//	
//	public CmtbGroup getCmtbGroup() {
//		return cmtbGroup;
//	}
//
//	public void setCmtbGroup(CmtbGroup cmtbGroup) {
//		this.cmtbGroup = cmtbGroup;
//	}


//	public String getUserId() {
//		return userId;
//	}
//
//	public void setUserId(String userId) {
//		this.userId = userId;
//	}

	public Long getGroupNo() {
		return groupNo;
	}

	public void setGroupNo(Long groupNo) {
		this.groupNo = groupNo;
	}

//	public List<CmtbSchedule> getCmtbScheduleSet() {
//		return cmtbScheduleSet;
//	}
//
//	public void setCmtbScheduleSet(List<CmtbSchedule> cmtbScheduleSet) {
//		this.cmtbScheduleSet = cmtbScheduleSet;
//	}
		
}
