package com.skan.potal.web.potal.application.model;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 공통코드 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table
public class CmtbCode implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 코드 관리번호. */
	@Id
	private String codeMgtNo;

	/** 상위코드. */
	private String upperCode;

	/** 그룹별 코드 순번. */
	private Long codeSeq;

	/** 코드. */
	private String code;

	/** 코드이름. */
	private String codeName;

	/** 코드 설명. */
	private String codeComment;

	/**
	 * 생성자.
	 */
	public CmtbCode() {
	}

	/**
	 * 코드 관리번호을 설정합니다..
	 * 
	 * @param codeMgtNo
	 *            코드 관리번호
	 */
	public void setCodeMgtNo(String codeMgtNo) {
		this.codeMgtNo = codeMgtNo;
	}

	/**
	 * 코드 관리번호을 가져옵니다..
	 * 
	 * @return 코드 관리번호
	 */
	public String getCodeMgtNo() {
		return this.codeMgtNo;
	}

	/**
	 * 상위코드을 설정합니다..
	 * 
	 * @param upperCode
	 *            상위코드
	 */
	public void setUpperCode(String upperCode) {
		this.upperCode = upperCode;
	}

	/**
	 * 상위코드을 가져옵니다..
	 * 
	 * @return 상위코드
	 */
	public String getUpperCode() {
		return this.upperCode;
	}

	/**
	 * 그룹별 코드 순번을 설정합니다..
	 * 
	 * @param codeSeq
	 *            그룹별 코드 순번
	 */
	public void setCodeSeq(Long codeSeq) {
		this.codeSeq = codeSeq;
	}

	/**
	 * 그룹별 코드 순번을 가져옵니다..
	 * 
	 * @return 그룹별 코드 순번
	 */
	public Long getCodeSeq() {
		return this.codeSeq;
	}

	/**
	 * 코드을 설정합니다..
	 * 
	 * @param code
	 *            코드
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * 코드을 가져옵니다..
	 * 
	 * @return 코드
	 */
	public String getCode() {
		return this.code;
	}

	/**
	 * 코드이름을 설정합니다..
	 * 
	 * @param codeName
	 *            코드이름
	 */
	public void setCodeName(String codeName) {
		this.codeName = codeName;
	}

	/**
	 * 코드이름을 가져옵니다..
	 * 
	 * @return 코드이름
	 */
	public String getCodeName() {
		return this.codeName;
	}

	/**
	 * 코드 설명을 설정합니다..
	 * 
	 * @param codeComment
	 *            코드 설명
	 */
	public void setCodeComment(String codeComment) {
		this.codeComment = codeComment;
	}

	/**
	 * 코드 설명을 가져옵니다..
	 * 
	 * @return 코드 설명
	 */
	public String getCodeComment() {
		return this.codeComment;
	}

}
