package com.skan.tms.web.jpa.dto;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * 좌석 등급 배치도 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table
public class SeatLevelChart implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;
	
	@Id 
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer seatLevelChartSeq; 
	
	/** 좌석 등급 배치도 관리. */
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="seatChartId", nullable=false , updatable=false, insertable=true)
	@JsonIgnore
	private SeatLevelChartManagement seatLevelChartManagement;

	/** 좌석 아이디. */
	private Integer seatId;

	/** 층수 (1층, 2층). */
	private Integer floor;

	/** 구역명. */
	private String areaName;

	/** 열명칭 . */
	private String rowName;

	/** 좌석번호. */
	private Integer seatNumber;

	/** 좌석 등급 아이디. */
	private Integer gradeId;

	/** 상태 (정상/홀딩/고장). */
	private String status;
	
	/**
	 * 색상
	 */
	@Transient private String gradeColor;
	
	/**
	 * 공연장명
	 */
	@Transient private String concertHallName;
	
	

	public String getConcertHallName() {
		return concertHallName;
	}


	public void setConcertHallName(String concertHallName) {
		this.concertHallName = concertHallName;
	}


	/**
	 * 생성자.
	 */
	public SeatLevelChart() {
	}
	

	public SeatLevelChart(
			Integer seatLevelChartSeq, 
			Integer seatId, 
			String areaName,
			Integer floor, 
			String rowName, 
			Integer seatNumber, 
			Integer gradeId, 
			String status, 
			String gradeColor,
			String concertHallName) {
		super();
		this.seatLevelChartSeq = seatLevelChartSeq;
		this.seatId = seatId;
		this.floor = floor;
		this.areaName = areaName;
		this.rowName = rowName;
		this.seatNumber = seatNumber;
		this.gradeId = gradeId;
		this.status = status;
		this.gradeColor = gradeColor;
		this.concertHallName = concertHallName;
	}




	/**
	 * 좌석 등급 배치도 관리을 설정합니다..
	 * 
	 * @param seatLevelChartManagement
	 *            좌석 등급 배치도 관리
	 */
	public void setSeatLevelChartManagement(SeatLevelChartManagement seatLevelChartManagement) {
		this.seatLevelChartManagement = seatLevelChartManagement;
	}

	/**
	 * 좌석 등급 배치도 관리을 가져옵니다..
	 * 
	 * @return 좌석 등급 배치도 관리
	 */
	public SeatLevelChartManagement getSeatLevelChartManagement() {
		return this.seatLevelChartManagement;
	}
	

	public String getgradeColor() {
		return gradeColor;
	}

	public void setgradeColor(String gradeColor) {
		this.gradeColor = gradeColor;
	}

	
	public Integer getSeatLevelChartSeq() {
		return seatLevelChartSeq;
	}

	public void setSeatLevelChartSeq(Integer seatLevelChartSeq) {
		this.seatLevelChartSeq = seatLevelChartSeq;
	}

	/**
	 * 좌석 아이디을 설정합니다..
	 * 
	 * @param seatId
	 *            좌석 아이디
	 */
	public void setSeatId(Integer seatId) {
		this.seatId = seatId;
	}

	/**
	 * 좌석 아이디을 가져옵니다..
	 * 
	 * @return 좌석 아이디
	 */
	public Integer getSeatId() {
		return this.seatId;
	}

	/**
	 * 층수 (1층, 2층)을 설정합니다..
	 * 
	 * @param floor
	 *            층수 (1층, 2층)
	 */
	public void setFloor(Integer floor) {
		this.floor = floor;
	}

	/**
	 * 층수 (1층, 2층)을 가져옵니다..
	 * 
	 * @return 층수 (1층, 2층)
	 */
	public Integer getFloor() {
		return this.floor;
	}

	/**
	 * 구역명을 설정합니다..
	 * 
	 * @param areaName
	 *            구역명
	 */
	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	/**
	 * 구역명을 가져옵니다..
	 * 
	 * @return 구역명
	 */
	public String getAreaName() {
		return this.areaName;
	}

	/**
	 * 열명칭 을 설정합니다..
	 * 
	 * @param rowName
	 *            열명칭 
	 */
	public void setRowName(String rowName) {
		this.rowName = rowName;
	}

	/**
	 * 열명칭 을 가져옵니다..
	 * 
	 * @return 열명칭 
	 */
	public String getRowName() {
		return this.rowName;
	}

	/**
	 * 좌석번호을 설정합니다..
	 * 
	 * @param seatNumber
	 *            좌석번호
	 */
	public void setSeatNumber(Integer seatNumber) {
		this.seatNumber = seatNumber;
	}

	/**
	 * 좌석번호을 가져옵니다..
	 * 
	 * @return 좌석번호
	 */
	public Integer getSeatNumber() {
		return this.seatNumber;
	}

	/**
	 * 좌석 등급 아이디을 설정합니다..
	 * 
	 * @param gradeId
	 *            좌석 등급 아이디
	 */
	public void setGradeId(Integer gradeId) {
		this.gradeId = gradeId;
	}

	/**
	 * 좌석 등급 아이디을 가져옵니다..
	 * 
	 * @return 좌석 등급 아이디
	 */
	public Integer getGradeId() {
		return this.gradeId;
	}

	/**
	 * 상태 (정상/홀딩/고장)을 설정합니다..
	 * 
	 * @param status
	 *            상태 (정상/홀딩/고장)
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * 상태 (정상/홀딩/고장)을 가져옵니다..
	 * 
	 * @return 상태 (정상/홀딩/고장)
	 */
	public String getStatus() {
		return this.status;
	}


}
