<%@ taglib prefix="c"			uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt"			uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="dt"			uri="http://jakarta.apache.org/taglibs/datetime-1.0"%>
<%@ taglib prefix="fn" 			uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="spring" 		uri="/WEB-INF/taglib/spring.tld" %>

<%@ taglib prefix="date" 		uri="/WEB-INF/taglib/date.tld" %>
<%@ taglib prefix="code" 		uri="/WEB-INF/taglib/commonCode.tld" %>

